# Generated by Django 4.2.4 on 2023-08-12 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCaterogorie',
            fields=[
                ('inverntory_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySupplier',
            fields=[
                ('inventory_supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('adress', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('inventory_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inventory_supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorysupplier')),
                ('inverntory_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorycaterogorie')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_picture_url',
            fields=[
                ('inventory_picture_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('filepath', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('size', models.IntegerField(default=0)),
                ('file_format', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('inventory_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryproduct')),
            ],
        ),
    ]
